options {
STATIC = false ;
}
PARSER_BEGIN(Adder)
class Adder {
public static void main( String[] args )
throws ParseException, TokenMgrError, NumberFormatException {
Adder parser = new Adder( System.in ) ;
int val = parser.Start() ;
System.out.println(val); }
}
PARSER_END(Adder)


SKIP : { " " }
SKIP : { "\n" | "\r" | "\r\n" }
TOKEN : { < PLUS : "+" > }
TOKEN : { < NUMBER : (["0"-"9"])+ > }



int Start() throws NumberFormatException :
{
Token t ;
int i ;
int value ;
}
{
t = <NUMBER>
{ i = Integer.parseInt( t.image ) ; }
{ value = i ; }
(
<PLUS>
t = <NUMBER>
{ i = Integer.parseInt( t.image ) ; }
{ value += i ; }
)*
<EOF>
{ return value ; }
}