/* Generated By:JavaCC: Do not edit this line. TDConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TDConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int operand = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"or\"",
    "\"and\"",
    "\"not\"",
    "\"(\"",
    "\")\"",
    "<operand>",
  };

}
